CONTRIBUTING.md
DCO
README.md

- Add more content to README.md
- Add CONTRIBUTING.md
- Add DCO
The documents are derived from kubectl-rook-ceph[1] and ramen[2].
[1] https://github.com/rook/kubectl-rook-ceph
[2] https://github.com/RamenDR/ramen
Fixes: #1

Basic docs

---

.gitignore
Makefile
cmd/commands/init.go
cmd/commands/root.go
cmd/commands/test.go
cmd/commands/validate.go
cmd/main.go
examples/odf.go
go.mod
go.sum
pkg/config/config.go
pkg/console/console.go
pkg/test/clean.go
pkg/test/run.go
pkg/validate/clusters.go

Add ramenctl module, providing:                                                                                                                           
- cmd/main.go - the ramenctl command
- examples/odf.go - example of integrating in odf cli 
- cmd/commands - cobra command wrappers used by ramenctl. This is a
separate package to allow easy integration with other tools such as
odf cli.
- pkg/console - report progress, completion and errors to the console
- pkg/test - test stub implementation
- pkg/config - create sample configuration file
- pkg/validate - validate stub implementation
We follow the structure of the kubectl-rook-ceph project to make it easy
integrate with the odf cli project.
The command does not do much, but we can play with it to evaluate the user
experience.
Example …

Add basic command infrastructure

---

pkg/config/config.go

- Don't use commented values since it is hard to uncomment yaml objects                                               
- More clear default values
- Add new name property for clusters
- Add titles for configuration sections using ##
- Document which value may need to be modified or added
- Add missing options: repo, dr-policy, clusterset, tests
- Rename creator to commandName
- Use Go template to render the sample config, preparing for creating sample for drenv environment.
```yaml
clusters:
hub:
name: hub
kubeconfig: hub/config
c1:
name: primary
kubeconfig: primary/config
c2:
name: secondary
kubeconfig: secondary/config
repo:
url: https://github.com/RamenDR/ocm-ramen-samples.git
branch: main
drPolicy: dr-policy
clusterSet: default
PVCSpecs:
- name: rbd
storageClassName: rook-ceph-block …
```

Improve sample config

---

examples/odf.go

We used RootCmd.DisaplayName() to return "ramenctl" or "odf dr" as the command name use in the sample configuration file. This requires annotating RootCmd.
Example usage:
% examples/odf dr init -c odf.yaml
✅ Created config file "odf.yaml" - please modify for your clusters
% head -1 odf.yaml
Fixes #45

Fix command name when running as "odf dr"

---

Makefile
cmd/commands/root.go
examples/odf.go
pkg/build/build.go

Generate version from git description and report it in --version.
Add new build package keeping `build.Version` and `build.Commit`. `build.Version` is used by the root command to enable Cobra builtin --version option.
ramenctl commands report summary will include build.Version and build.Commit.
Example run when building from tag:
% ramenctl --version
v0.2.0
Example run for development build:
% ramenctl --version
v0.1.0-1-gbcb8824
The --version option is available only if pkg/build.Version is set. When building as "odf dr" the version flag will not be available, but odf cli can set build.Version and build.Commit for odf dr reports. The example was updated to show this usage.
Fixes #46

Add build information

---

cmd/commands/init.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/envfile.go
pkg/config/sample.yaml
pkg/config/testdata/regional-dr.yaml

This PR improves the ramenctl init command by supporting an optional environment file.
Environment File (--envfile) Support:
- Allows users to provide an environment file containing cluster information.
- If specified, the configuration is loaded from the environment file.
- If --envfile is not provided, a sample configuration file is created.
Example:
```
$ ./ramenctl init --envfile /home/oviner/test/regional-dr.yaml -c config50.yaml
⭐ Created new config file "config50.yaml"
✅ Finalized config file "config50.yaml" - please modify as needed            
$ cat config50.yaml 
clusters:
hub:
name: hub
kubeconfig: /home/oviner/.config/drenv/rdr/kubeconfigs/hub
c1:
name: dr1
kubeconfig: /home/oviner/.config/drenv/rdr/kubeconfigs/dr1
c2:
name: dr2
kubeconfig: …
```

Enhance init command to support ramen envfile

---

pkg/console/console.go
pkg/test/clean.go
pkg/test/command.go
pkg/test/report.go
pkg/test/run.go
pkg/test/test.go

Run all tests in parallel similar to ramen/e2e tests.
Improve the output to more more clear when running multiple tests by separating the output to multiple groups of steps.
Using 2 tests, expected usage for ramenctl.
```console
% ramenctl test run -o test
⭐ Using report "test"
🔎 Setup environment ...
✅ Environment setup
🔎 Run tests ...
✅ Application "appset-deploy-rbd" deployed
✅ Application "appset-deploy-cephfs" deployed
✅ Application "appset-deploy-cephfs" protected
✅ Application "appset-deploy-rbd" protected
✅ Application "appset-deploy-cephfs" failed over
✅ Application "appset-deploy-rbd" failed over
✅ Application "appset-deploy-cephfs" relocated
✅ Application "appset-deploy-rbd" relocated
✅ Application "appset-deploy-cephfs" unprotected
✅ Application …
```

test: Run all tests in parallel

---

pkg/report/report.go
pkg/report/report_test.go

- Omit build info if we have no build info
- Omit Version or Commit if empty
- Rename "ramenctl" to "build"
```yaml
build:
commit: 3273486bc215e59337eedfd88f67962b6505f17b
version: v0.2.0-2-g3273486
host:
arch: arm64
cpus: 12
os: darwin
name: test-run
status: passed
...
```

report: Improve build info

---

pkg/console/console.go
pkg/test/command.go
pkg/test/test.go

We use to log a very verbose errors to the console like:
❌ failed to failover application "appset-deploy-rbd": Get
"https://192.168.105.33:6443/apis/ramendr.openshift.io/v1alpha1/namespaces/argocd/drplacementcontrols/appset-deploy-rbd":
dial tcp 192.168.105.33:6443: connect: operation timed out
This is way too long and detailed for the console, and we may log multiple errors like this in some cases. This is not a good user experience.
Change to log only the high level message:
❌ failed to failover application "appset-deploy-rbd"
I triggered an error by stopping the hub cluster during the run.
% ramenctl test run -o test
⭐ Using report "test"
🔎 Setup environment ...
✅ Environment setup
🔎 Run tests ...
✅ Application …

test: Less verbose errors in console

---

Makefile

If you create a directory "test", running `make test` or `make clean` will do nothing:
% make test
make: `test' is up to date.
Fixed by making them .PHONY.

build: Make test and clean .PHONY

---

pkg/test/command.go
pkg/test/report.go
pkg/test/report_test.go
pkg/test/test.go

Change report structure to support nested steps. This will allow
grouping validation and setup steps in to single prepare step and adding
test steps (deploy, protect, ...) and timing info to the report.
To keep the structure consistent we include now the test name. This
makes it easier to relate to the test output and easier to follow.
```console
🔎 Setup environment ...
✅ Environment setup
🔎 Run tests ...
✅ Application "appset-deploy-rbd" deployed
✅ Application "appset-deploy-cephfs" deployed
✅ Application "appset-deploy-rbd" protected
✅ Application "appset-deploy-cephfs" protected
✅ Application "appset-deploy-cephfs" failed over
✅ Application "appset-deploy-rbd" failed over
✅ Application "appset-deploy-cephfs" relocated
✅ Application …
```

Support report with nested steps

---

go.mod
go.sum
pkg/config/sample.yaml

Updated to latest ramen/e2e to include [feature](https://github.com/RamenDR/ramen/issues/1907) added to detect the distro. 
Removed the distro config from the sample.
tested `ramenctl test run` command on ocp and drenv:
All tests passed and autodetected distro on both env.
ocp:
```
2025-03-27T20:34:44.755+0530	INFO	validate/validation.go:202	Detected kubernetes distribution: "ocp"
2025-03-27T20:34:44.755+0530	INFO	validate/validation.go:203	Using namespaces: {RamenHubNamespace:openshift-operators RamenDRClusterNamespace:openshift-dr-system RamenOpsNamespace:openshift-dr-ops ArgocdNamespace:openshift-gitops}
```
drenv:
```
2025-03-27T20:55:19.320+0530	INFO	validate/validation.go:202	Detected kubernetes distribution: "k8s"
2025-03-27T20:55:19.321+0530	INFO	validate/validation.go:203	Using …
```

Auto detect distro 

---

go.mod
go.sum
pkg/config/config.go
pkg/config/envfile.go
pkg/config/sample.yaml

We dont need users to specify cluster names
anymore since managed cluster names will be
auto detected and hub cluster name will always
be hub.
Also removed cluster name lookup from envfile
since drenv conf will not have cluster names anymore.
These changes are due  to feature added in ramen/e2e:
https://github.com/RamenDR/ramen/issues/1866

config: Remove cluster names from sample config

---

pkg/config/sample.yaml

We don't allow cluster name configuration now, it is automatically discovered during startup.
This change was missing in #80.

init: Remove stale note about cluster name

---

go.mod
go.sum

To consume fixes for OpenShift console compatibility:
- https://github.com/RamenDR/ramen/pull/1989
- https://github.com/RamenDR/ramen/pull/1991
With these fixes we would be able to see and manipulate the test
application in the console. This can be useful for manually cleaning up
if `test clean` was not run.

Update ramen/e2e to latest version

---

README.md

- We downloaded the executable, but the install command failed because of typo.
- Make the curl command more robust and clear, failing on errors instead of creating invalid executable.
Tested with my fork:
https://github.com/nirs/ramenctl/tree/v0.3.4-rc2
```console
tag="$(curl -fsSL https://api.github.com/repos/nirs/ramenctl/releases/latest | jq -r .tag_name)"
os="$(uname | tr '[:upper:]' '[:lower:]')"
machine="$(uname -m)"
if [ "$machine" = "aarch64" ]; then machine="arm64"; fi
if [ "$machine" = "x86_64" ]; then machine="amd64"; fi
curl --location --fail --silent --show-error --output ramenctl \
https://github.com/nirs/ramenctl/releases/download/$tag/ramenctl-$tag-$os-$machine
sudo install ramenctl /usr/local/bin/
rm ramenctl
% /usr/local/bin/ramenctl -v
v0.3.4-rc2
```

Fix install script and make it more robust and clear

---

.gitignore
Makefile
pkg/config/config.go
pkg/config/config_test.go
pkg/config/envfile.go
pkg/config/sample.go
pkg/config/sample.yaml

When running as `odf dr` use the default ODF storage class names that                                                                      
are more likely to work instead of drenv storage class name, that will
never work. This minimizes manual configuration, making `odf dr` easier
to use.
When using the --envfile flag we use default drenv storage classes since
envfile is never needed for ODF cluster. Currently the envfile does not 
include the storage class names so we must hard code them in ramenctl.
This makes it possible to use `odf dr init` with a drenv environment,
which can help developer that work mostly with an ODF cluster.
We can consider later smarter way to configure the storage classes like
listing the available storage classes and let the user choose.
To make the change easy …

 init: Optimize storage classes for ODF

---

docs/testing.md

The testing guide shows how to test disaster recovery with ODF clusters.
This will be used to create a KCS for ODF, and can be used for testing `ramenctl` and`odf dr` commands.
Preview in my fork:
https://github.com/nirs/ramenctl/blob/testing-guide/docs/testing.md

docs: Add a testing guide

---

pkg/config/sample.yaml

Both PVCSpecs and pvcSpecs works since viper config is case insensitive, but we document pvcSpecs.
Thanks: Annette Clewett

Fix spelling of pvcSpecs

---

pkg/report/report.go
pkg/report/report_test.go
pkg/test/report_test.go

This should be a trivial change but Go made it harder since time.Time includes monotonic time value that break serialization. We fix using .Local() returning local time without monotonic time info.
Another complication is testing - new report.Now() was added to allow the test to freeze report time during the tests.
Example report:
% head test/test-run.yaml
build:
commit: 93ddc8584ad5017842e56f44044c27558f7f5483
version: v0.3.5
created: "2025-04-09T18:55:57.087804+03:00"
host:
arch: arm64
cpus: 12
os: darwin
name: test-run
status: passed
Fixes: #64

Add report creation time

---

.github/workflows/test.yaml
Makefile
go.mod
pkg/report/report.go
pkg/report/report_test.go
pkg/test/report.go
pkg/test/report_test.go

We want to ensure that ramenctl works on all supported platforms. The best way to do this is to run the unit tests.
Add test matrix job running on all available github runners[1]:
- ubuntu-24.04 (x86_64)
- ubuntu-24.04-arm (arm64)
- windwos-latest (x86_64)
- macos-13 (x86_64)
- macos-15 (arm64)
On each runner we build the executables and run the tests.
We cannot use the build job since all jobs run on ubuntu-latest (x86_64) and we use cross compiling to build the executables for all os and architectures.
[1] https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
Fixes: #42

ci: Run tests on all platforms and architectures

---

cmd/commands/root.go
cmd/commands/test.go
cmd/commands/validate.go

When we made --output required, we left unused code and incorrect default value:
Flags:
-h, --help            help for test
-o, --output string   report directory (default report.{timestamp})
Remove outputDir() helper and rename userOutputDir to outputDir. The code using this flag access the value via the global variable.
Example help:
Flags:
-h, --help            help for test
-o, --output string   output directory

cmd: Remove leftovers after requiring --output

---

pkg/test/report.go
pkg/test/report_test.go
pkg/test/test.go

When a test fails, we want to know which step failed. In the future we
want to support running single steps (#78) or configurable test flows
(#84). In both case we want an easy way to know what was the tested
flow. We can learn about the tested flow from the logs but it is much
easier and quicker when the information is part of the report.
Example test run:
```console
% cat test/test-run.yaml
build:
commit: e7f811d652c91383227c115c006b9ad883efc12b
version: v0.3.5-2-ge7f811d
host:
arch: arm64
cpus: 12
os: darwin
name: test-run
status: passed
steps:
- name: validate
status: passed
- name: setup
status: passed
- items:
- config:
deployer: appset
pvcSpec: rbd
workload: deploy
items:
- name: deploy
status: passed
- name: protect
status: passed
- name: failover
status: passed
- name: relocate …
```

test: Report test steps

---

.github/workflows/test.yaml

Upload the built executables so they are available for download from the                                                                         
build page. This will be useful for testing PRs by non-developers,
saving the time to build and send files manually.
We use a special tag "build-14503707498-1", corresponding to
https://github.com/RamenDR/ramenctl/actions/runs/14503707498/attempts/1.
The build tag is reported in --version:
$ ramenctl --version
build-14503707498-1
And in the report build info:
build:
version: build-14503707498-1
commit: 375a5318b851ce1fb3f70c0c02a69b3f454a2992
On macOS executables downloaded by the browser are considered unsafe and                                                                         
cannot run. To remove the protection run:
xattr -d …

build: Upload built executables

---

go.mod
go.sum

This updates ramen/e2e to include the following validations and improvements:
- PVCSpec config validation:
- Detects duplicate PVCSpec names and contents
- Validates storageClassName format (RFC1123)
- Validates accessModes are valid and supported
- Verifies storageClass exists in both managed clusters
- Removed the unused UnsupportedDeployers field from PVCSpec
Example validation messages in ramenctl:
- Duplicate PVCSpec names:
❌ failed to read config "config.yaml": unable to read config: duplicate pvcSpec name "rbd" found: {Name:rbd StorageClassName:rook-ceph-block AccessModes:ReadWriteOnce} {Name:rbd StorageClassName:rook-cephfs-fs1 AccessModes:ReadWriteMany}
- Duplicate PVCSpec content:
❌ failed to read config "config.yaml": unable to read config: duplicate pvcSpec content found: …

update ramen/e2e to include PVCSpec validation

---

pkg/report/report.go
pkg/test/report.go

When comparing the same pointer we can return early.

report: Shortcut comparing to itself

---

docs/testing.md
go.mod
go.sum
pkg/test/command.go
pkg/test/report.go
pkg/test/report_test.go

This PR updates ramen/e2e dependency to include Config.Equal support and test report now includes *types.Config field
to capture test configuration in the report.
Report testing:
1. ramenctl test run:
```
build:
commit: de6950adf6666a4ff0886e29e99a998615142fe5
version: v0.4.0-7-gde6950a
config:
channel:
name: https-github-com-ramendr-ocm-ramen-samples-git
namespace: test-gitops
clusterSet: default
clusters:
c1:
kubeconfig: /Users/pari/.config/drenv/rdr/kubeconfigs/dr1
c2:
kubeconfig: /Users/pari/.config/drenv/rdr/kubeconfigs/dr2
hub:
kubeconfig: /Users/pari/.config/drenv/rdr/kubeconfigs/hub
distro: k8s
drPolicy: dr-policy
namespaces:
argocdNamespace: argocd
ramenDRClusterNamespace: ramen-system
ramenHubNamespace: ramen-system
ramenOpsNamespace: ramen-ops
pvcSpecs:
- accessModes: …
```

Include test config in report

---

docs/testing.md
go.mod
go.sum
pkg/command/command.go
pkg/test/clean.go
pkg/test/command.go
pkg/test/context.go
pkg/test/report.go
pkg/test/report_test.go
pkg/test/run.go
pkg/test/test.go

When a user interrupt a ramenctl command we want to cancel if-flight steps and write a report with the canceled steps. To make this possible ramen/e2e added cancellation support using context.Context.
We have a new Canceled status, used for steps that failed with context.Canceled error. Adding a canceled step makes the containing step and the entire report canceled.
The command.Command and test.Command types implement ramen/e2e/types.Context. We create a cancellable context when creating command.Command. The command starts a signal handler that will cancel the context when receiving a SIGINT signal. Cancelling the context will cancel the e2e calls and mark the report as canceled.
I scale down the rbd-mirror deployment on cluster dr2 to fail the rbd applications to fail in the protect …

Support cancellation

---

pkg/command/command.go
pkg/command/log.go
pkg/e2e/e2e.go
pkg/e2e/testing.go
pkg/test/clean.go
pkg/test/command.go
pkg/test/command_test.go
pkg/test/context.go
pkg/test/mock.go
pkg/test/run.go
pkg/test/test.go

Add fast tests for entire test commands.
Currently testing test.Command requires a real cluster and take about 10 minutes for the simplest flow. We want to test multiple positive and negative flows in milliseconds.
To make this possible, we need to use a mock e2e interface that succeeds immediately without accessing any cluster, and allow simulating errors for particular workloads, deployers, or actions.
We change test.Command to accept a command.Command, so we can create it with a plain command created by the tests with a config, env, and log configured for the test.
Instead of using the e2e packages directly, we use a backend implementing a testing interface providing all the operations that e2e provides. During the test we use a MockBackend that succeeds immediately. The backend can be …

Add fast command tests

---

go.mod
go.sum
pkg/test/command.go
pkg/test/command_test.go
pkg/test/test.go

Implemented Test.Cleanup() to undeploy the application and
disable protection concurrently.
Testing:
1. Scaled down the rbd-mirror deployment on cluster dr2 to fail the applications in the protect step.
```
./ramenctl test run -o run
⭐ Using report "run"
🔎 Setup environment ...
✅ Environment setup
🔎 Run tests ...
✅ Application "appset-deploy-cephfs" deployed
✅ Application "appset-deploy-rbd" deployed
✅ Application "disapp-deploy-rbd" deployed
✅ Application "disapp-deploy-cephfs" deployed
✅ Application "subscr-deploy-cephfs" deployed
✅ Application "subscr-deploy-rbd" deployed
✅ Application "disapp-deploy-cephfs" protected
✅ Application "subscr-deploy-cephfs" protected
✅ Application "appset-deploy-cephfs" protected
✅ …
```

Update cleanFlow to run unprotect and undeploy parallel

---

docs/testing.md
pkg/command/command.go

This pull request fixes several typos:
- `ouput` → `output`
- `develpers` → `developers`
- `cancelation` → `cancellation`
The typo `ot` in `go.sum` appears to be part of hash values and was left unchanged to avoid breaking code integrity.
Let me know if there are any other edits you'd like me to make!
Fixes #134

Fix typos in testing.md and command.go

---

README.md

Add list of guides in the Documentation section.
Preview:
https://github.com/nirs/ramenctl/tree/readme-docs?tab=readme-ov-file#documentation
Fixes: #125

docs: Link to testing guide

---

docs/testing.md
pkg/report/report.go
pkg/report/report_test.go
pkg/test/command.go
pkg/test/report.go
pkg/test/report_test.go
pkg/test/test.go
pkg/time/time.go

Updated report to record duration of test steps and overall test execution
This allows timing info to be included in test reports for for better timing and performance insights.
Testing:
1. test run report:
```
build:
commit: c2907b0328599ccbded336602f57b0a26854068a
version: v0.4.0-23-gc2907b0
config:
....
created: "2025-05-05T18:35:44.587494+05:30"
duration: 695.608462543
host:
arch: arm64
cpus: 12
os: darwin
name: test-run
status: passed
steps:
- duration: 0.022823334
name: validate
status: passed
- duration: 0.009449584
name: setup
status: passed
- duration: 695.576189625
items:
- config:
deployer: appset
pvcSpec: rbd
workload: deploy
duration: 695.576118209
items:
- duration: 0.013429167
name: deploy
status: passed
- duration: 95.095957834
name: protect
status: passed
- duration: …
```

Add duration tracking for test and command steps

---

pkg/test/report.go

When we renamed Time to Duration we forgot to rename the tags. We want to use the same name for consistency. We may wan to add "time" later for the time the step was started.

report: Fix Duration tags

---

pkg/time/time.go

Removing unintended comment in time.go module added as part of PR: https://github.com/RamenDR/ramenctl/pull/130

remove unintended comment in time.go module

---

.github/workflows/release.yaml
.github/workflows/test.yaml

When workflow do no specify permissions, they inherit the permissions
from the repository permissions. Often these permissions do not adhere
to the principle of least privilege and can be reduced to read-only.
The test workflows does not need to change anything in the repository so
it should use read-only permission.
Fixes #144

build: Harden workflow permissions

---

.editorconfig
CONTRIBUTING.md

- Add .editorconfig file to help contributor configure their editor automatically
- Update code style section in the contribution guide
Fixes #143

build: Add EditorConfig file

---

pkg/test/report.go

The fix addresses this by modifying the status priority logic for AddTest and AddStep:
- "Canceled" now has the highest priority and will override any other status
- "Failed" will only be set if the current status isn't already "Canceled"
This ensures that once a step has a "Canceled" status, it won't be changed to "Failed" by subsequently added tests.
Fixes #155

report: update status logic for Failed and Canceled

---

pkg/test/report_test.go

Add minor cleanups to report tests:
- Missing test cases
- Move sub tests to correct test
- Shorter sub test names
- Unify variable name style
- Simplify tests
- Improve test documentation

Report tests cleanups

---

.github/workflows/test.yaml
Makefile
docs/testing.md
pkg/test/report_test.go

This PR adds automated spell checking to our codebase and fixes existing spelling errors:
1. Added spell checking:
- Created a separate "spell" job in the CI workflow using the official codespell-project/actions-codespell@v2 GitHub Action
- Added a matching make spell command for local development
- Configured both to skip go.sum.
2. Fixed existing spelling errors :
```
$ make spell
codespell --skip="go.sum"
./docs/testing.md:369: runnning ==> running
./pkg/test/report_test.go:153: cancled ==> canceled
temp
./pkg/test/report_test.go:166: cancled ==> canceled
./pkg/test/report_test.go:505: Addding ==> Adding
```
Fixes: #133

Add spell checking to CI workflow and fix spelling errors

---

pkg/command/command.go
pkg/test/command.go
pkg/test/context.go
pkg/test/report_test.go
pkg/test/test.go

Next ramen/e2e version will use context deadline instead of internal timeouts. To consume it we must pass a types.Context and types.TestContext with the right deadline.
Like ramen/e2e we implement WithTimeout on the concrete types (command.Command, test.Context) and use it to create a context with a deadline before we pass the context to ramen/e2e.
Additionally we add deadlines to validate and setup operations which do not use a deadline in e2e. This should be fixed in e2e to ensure quick failure for these operations.
With current ramen/e2e, this change limit the time we wait for testing operations, in case when we have multiple wait loops for the same operation (e.g. failover). With this change the entire operation will time out after 10 minutes, even if e2e try to wait 10 minutes per …

test: Use context deadline for all operations

---

go.mod
go.sum

Consuming fix for deleting resources and waiting for deletion: https://github.com/RamenDR/ramen/pull/2035
Fixes: #187

deps: Update ramen/e2e to latest version

---

go.mod
go.sum
pkg/command/command.go
pkg/config/config.go
pkg/test/command.go
pkg/test/command_test.go
pkg/test/context.go
pkg/test/report.go
pkg/test/report_test.go
pkg/test/test.go

Require latest ramen/2e including new API changes: https://github.com/RamenDR/ramen/pull/2088
Adapt to use the new API:
- types.Config and related types were moved to the config package
- env.New takes now clusters map instead of config
- util.Timeout replaced with per-operation timeout
This change reduces the chance of random timeouts during failover and relocate, after adding wait for application health that we already consumed recently.

deps: Adapt to new ramen/e2e API

---

docs/testing.md
pkg/report/report.go
pkg/report/report_test.go
pkg/test/command.go
pkg/test/command_test.go
pkg/test/report.go
pkg/test/report_test.go
pkg/test/test.go

Move state and code to the generic report package so we can use it for all commands. The test.Report is minimized to add the test specific state and code for managing tests steps.
This change drops the test config, since it is not generic, and makes it harder to create the generic report. We can consider adding it later in a more generic way.
Testing
Fixes #194

Generic report for any ramenctl command

---

pkg/gather/gather.go

this commit adds duration field to results
struct in gather pkg.
We need duration to add in reports for other
pkg like test, validation and gather

gather: add durations to gather pkg

---

cmd/commands/gather.go
cmd/ramenctl.go
pkg/gather/command.go
pkg/gather/gather.go

this commit adds the gather command
infrastructure to collection
```console
$ ./ramenctl gather application --help
Collect data based on application
Usage:
ramenctl gather application [flags]
Flags:
-h, --help               help for application
--name string        drpc name
-n, --namespace string   drpc namespace
Global Flags:
-c, --config string   configuration file (default "config.yaml")
-o, --output string   output directory
```
```console
yatipadia:ramenctl$ ./ramenctl gather application -o gather -c ocp.yaml --name test-ns --namespace openshift-dr-ops
⭐ Using config "ocp.yaml"
⭐ Using report "gather"
🔎 Gather Application data ...
✅ Inspected application
✅ Gathered data from cluster "prsurve-c2-7j"
✅ Gathered data from cluster "hub"
✅ …
```

cmd: add gather command

---

pkg/validate/command.go
pkg/validate/command_test.go

This change implements gathering cluster resources, and adds stub for validating gathered cluster data.
Gatherring only the namespaces related to ramen ie hub and DR cluster namespaces, which contain the ramen resources needed for cluster validation.
```
./ramenctl validate clusters -o val
⭐ Using report "val"
🔎 Validate clusters ...
✅ Gathered data from cluster "dr2"
✅ Gathered data from cluster "hub"
✅ Gathered data from cluster "dr1"
✅ Clusters validated
✅ Validation completed
```
report:
```
build:
commit: a026a7b375dbc79ec3de5153798a88fae7b5c8b7
version: v0.8.0-28-ga026a7b
config:
clusterSet: default
clusters:
c1:
kubeconfig: /Users/pari/.config/drenv/rdr/kubeconfigs/dr1
c2:
kubeconfig: …
```

validate: Gather ramen namespaces for cluster validation

---

pkg/gather/command.go
pkg/gather/command_test.go
pkg/report/report.go
pkg/report/report_test.go

this commit adds namespaces to be gathered
by gather command to the report
Fixes: #179

add namespaces to gather to the report

---

go.mod

Update to go 1.24, same as the e2e pkg version in ramen.

go: update the go version

---

.github/workflows/release.yaml

The default is latest which is not bad, but let's have more predictable version by using the version specified in go.mod. This is also how we build in the test workflow.
Pre-release for testing: https://github.com/nirs/ramenctl/releases/tag/v0.9.0-pre1

release: Use go version from go.mod

---

pkg/gather/command.go
pkg/gather/command_test.go
pkg/sets/sets.go
pkg/test/command.go
pkg/validate/application.go
pkg/validate/clusters.go
pkg/validate/command_test.go

Like `gather application` command, `validate application` and `validated clusters` commands report now the gathered namespaces.
Add set.Sorted() helper to create sorted set of values, needed when building namespaces list to gather and for testing the gathered namespaces. We used this now in many commands and tests.
In cases when we must build sets dynamically we create a sorted slices using slices.Sorted().

Report gathered namespaces in validate commands and unify namespaces handling

---

go.mod
go.sum

This version introduced --cluster for for gathering only cluster scoped resources. Which will be used for validate cluster command.

deps: Update kubectl-gather to 0.10.0

---

pkg/validate/command_test.go
pkg/validate/testdata/appset-deploy-rbd/validate-application.data/dr1/namespaces/e2e-appset-deploy-rbd/ramendr.openshift.io/volumereplicationgroups/appset-deploy-rbd.yaml
pkg/validate/testdata/appset-deploy-rbd/validate-application.data/dr2/namespaces/e2e-appset-deploy-rbd/ramendr.openshift.io/volumereplicationgroups/appset-deploy-rbd.yaml
pkg/validate/testdata/appset-deploy-rbd/validate-application.data/hub/namespaces/argocd/ramendr.openshift.io/drplacementcontrols/appset-deploy-rbd.yaml

We test using mock backed so nothing is gathered, but need gathered data for testing validation. Add partial gathered data from ramen testing environment from appset-deploy-rbd test. We may want to test more applications later.
The test data is stored at `testdata/appset-deploy-rbd` so we can easily add more applications or cluster data for validating cluster tests.
The test constants and variables were updated to to match the test data. To add more application we will need to use different names for each applications.

validate: Add gathered data to tests

---

pkg/gather/command.go
pkg/gather/command_test.go
pkg/gathering/gathering.go
pkg/test/command.go
pkg/testing/backend.go
pkg/testing/mock.go
pkg/testing/testing.go
pkg/validate/application.go
pkg/validate/clusters.go
pkg/validate/command.go
pkg/validate/command_test.go
pkg/validation/backend.go
pkg/validation/mock.go
pkg/validation/validation.go

This PR address:
- adds Context interface with Logger() and Context() methods for gathering operations
- refactors by replacing individual parameters (namespaces, outputDir) with gathering.Options.
- add support for gather cluster scoped resources which will be used to validate clusters
Testing: 
```
./ramenctl validate clusters -o val
⭐ Using report "val"
🔎 Validate clusters ...
✅ Gathered data from cluster "hub"
✅ Gathered data from cluster "dr2"
✅ Gathered data from cluster "dr1"
✅ Clusters validated
✅ Validation completed
Gathers cluster scoped resources:
$ tree -L 4 val
val
├── validate-clusters.data
│   ├── dr1
│   │   ├── cluster
│   │   │   ├── apiextensions.k8s.io
│   │   │   ├── apiregistration.k8s.io
│   │   …
```

Gather cluster scoped resources to validate clusters

---

pkg/report/application_test.go
pkg/report/helpers_test.go

Relocated marshal() from application_test.go to helpers_test.go so it can be reused by multiple test files.

report: move marshal() test helper to helpers_test.go

---

pkg/report/application.go
pkg/report/application_test.go
pkg/report/validation.go
pkg/validate/application.go
pkg/validate/command.go
pkg/validate/command_test.go

The deleted property of all resources is defined now as:
```go
Deleted ValidatedBool `json:"deleted"`
```
If an object is not deleted we show:
```yaml
deleted:
state: ok ✅
```
If an object is missing we will see:
```yaml
deleted:
value: true
state: error ❌
description: Resource does not exist
```
If an object was deleted but still exists we show:
```yaml
deleted:
value: true
state: error ❌
description: Resource was deleted
```
I considered using *ValidatedBool so we don't show anything if the object is not deleted, but this does not add an OK validation to the summary, and does not show that we did any validation.
When handling a missing VRGs mark the VRG as deleted instead of aborting the validation. The validated step is marked as failed but we continue to validate all clusters. …

validate: Handle missing or deleted resources

---

pkg/validate/application.go
pkg/validate/command_test.go

In the VRG this condition has incompatible behavior when using volsync
and volrep. With volrep it is False in stable state and True during some
part of Relocate flow. With volsync it is True in stable state.
For protected PVCs the condition appears only for volrep using the
confusing semantics.
Fixed by dropping the condition since we have no sane way to validate
the state. The condition is available in the gathered resource user need
to inspect the value.
```console
% ramenctl validate application --name appset-deploy-rbd \
--namespace argocd -o out/appset-deploy-rbd
⭐ Using report "out/appset-deploy-rbd"
🔎 Validate application ...
✅ Inspected application
✅ Gathered data from cluster "dr2"
✅ Gathered data from cluster …
```

validate: Skip DataProtected condition

---

pkg/report/clusters.go
pkg/report/clusters_test.go

Include `RamenControllerType` in `ConfigMapSummary` to capture the type of Ramen controller (e.g., dr-hub, dr-cluster). Update equality checks and tests.
```
clusters:
- name: dr1
ramen:
configmap:
name: ramen-dr-cluster-operator-config
namespace: ramen-system
ramenControllerType:
state: ok ✅
value: dr-cluster
s3StoreProfiles:
state: ok ✅
value:
- s3ProfileName: s3-profile-dr1
s3SecretRef:
state: ok ✅
value:
name: ramen-s3-secret-dr1
namespace: ramen-system
- s3ProfileName: s3-profile-dr2
s3SecretRef:
state: ok ✅
value:
name: ramen-s3-secret-dr2
namespace: ramen-system
- name: dr2
ramen:
configmap:
name: ramen-dr-cluster-operator-config
namespace: ramen-system
ramenControllerType:
state: ok ✅
value: dr-cluster
s3StoreProfiles:
state: ok ✅
value:
- s3ProfileName: s3-profile-dr1 …
```

report: add RamenControllerType to ConfigMapSummary

---

pkg/report/application.go
pkg/report/application_test.go
pkg/validate/application.go
pkg/validate/command_test.go

Like phase, we mark only the stable progression as ok, and anything else
as an error. An application should now be in unstable progression for
long time. Possible case may be waiting for user action during failover
or relocate, or application stuck in failover or relocate because some
issue.
Example report:
```yaml
applicationStatus:
hub:
drpc:
action:
state: ok ✅
conditions:
- state: ok ✅
type: Available
- state: ok ✅
type: PeerReady
- state: ok ✅
type: Protected
deleted:
state: ok ✅
drPolicy: dr-policy
name: appset-deploy-rbd
namespace: argocd
phase:
state: ok ✅
value: Deployed
progression:
state: ok ✅
value: Completed
```
Part-of #262

Validate drpc progression

---

pkg/report/application.go
pkg/report/application_test.go
pkg/validate/application.go
pkg/validate/command_test.go

Same as drpc phase and progression, we mark the stable vrg state as ok,
and anything else as an error. The vrg on the primary cluster must have
Primary state, and the vrg on the secondary cluster must be Secondary
state. If an application does not show the right state for long time it
requires investigation.
Example report:
```yaml
applicationStatus:
hub:
drpc:
action:
state: ok ✅
conditions:
- state: ok ✅
type: Available
- state: ok ✅
type: PeerReady
- state: ok ✅
type: Protected
deleted:
state: ok ✅
drPolicy: dr-policy
name: appset-deploy-rbd
namespace: argocd
phase:
state: ok ✅
value: Deployed
progression:
state: ok ✅
value: Completed
primaryCluster:
name: dr1
vrg:
conditions:
- state: ok ✅
type: DataReady
- state: ok ✅
type: ClusterDataReady
- state: ok ✅
type: ClusterDataProtected
- …
```

Validate vrg state

---

pkg/report/application.go
pkg/report/application_test.go
pkg/validate/application.go
pkg/validate/command_test.go

Protected PVC must be bound; anything else seen for long time requires
investigation.
Example report:
```yaml
protectedPVCs:
- conditions:
- state: ok ✅
type: DataReady
- state: ok ✅
type: ClusterDataProtected
deleted:
state: ok ✅
name: busybox-pvc
namespace: e2e-appset-deploy-rbd
phase:
state: ok ✅
value: Bound
replication: volrep
state:
state: ok ✅
value: Primary
```
Tested with rbd and cephfs applications.
Fixes #262

Validate protected pvc phase

---

pkg/report/application.go
pkg/report/application_test.go
pkg/validate/application.go
pkg/validate/command_test.go

Use more standard `ApplicationStatusHub` and `ApplicationStatusCluster` to   
match `ClustersStatusHub` and `ClustersStatusClusters`.

report: Unify application status types

---

go.mod
go.sum
pkg/validate/clusters.go
pkg/validation/ocm.go

Update ramen/e2e to consume fix for RamenDR/ramen#2228 to use Env.ManagedCluster() method instead of slices with env.C1 and env.C2.
Fixes #309

 replace managed clusters with env.ManagedClusters()

---

go.mod
go.sum
pkg/command/command.go

We fail with a cleaner error and log the detailed error to the log,                                                                  
similar to other errors.                                                    
Example run with inaccessible cluster:                                      
% ramenctl validate clusters -o out/env-error
⭐ Using config "config.yaml"                                           
⭐ Using report "out/env-error"                                         
❌ failed to create env                                                 
% head -1 out/env-error/validate-clusters.log                           
2025-09-25T23:36:18.271+0300        ERROR   command/command.go:68       
Failed to create env: failed to create cluster "hub":                   
failed to build config from …

More user friendly error if creating env failed                                                                                      

---

pkg/report/clusters.go
pkg/report/clusters_test.go
pkg/report/validation.go
pkg/validate/clusters.go
pkg/validate/command_test.go

This PR adds support for reporting and validate peer classes if it does not exist in the DRPolicy status. 
Update report and validate clusters unit tests to include peer classes.
Testing:
1. OCP:
```
./ramenctl validate clusters -c out/ocp/ocp.yaml -o out/val_ocp
⭐ Using config "out/ocp/ocp.yaml"
⭐ Using report "out/val_ocp"
🔎 Validate clusters ...
✅ Gathered data from cluster "prsurve-s2-c1"
✅ Gathered data from cluster "prsurve-s2-c2"
✅ Gathered data from cluster "hub"
✅ Clusters validated
✅ Validation completed (37 ok, 0 stale, 0 problem)
```
report:
```
hub:
...
drPolicies:
state: ok ✅
value:
- conditions:
- state: ok ✅
type: Validated
drClusters:
- prsurve-s2-c1
- prsurve-s2-c2
name: odr-policy-5m
peerClasses:
state: ok ✅
value:
- …
```

validate: report and validate peer classes in drpolicy
